context:
  name: evo
  version: "1.32.0"
  python_min: 3.10

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
    sha256: 2d72d2413b0bd5879a95724c06b796008cde77126a1d21aae5e2d36b1c9eac68

build:
  noarch: python
  number: 0
  script: ${{ PYTHON }} -m pip install . --no-deps --no-build-isolation
  python:
    entry_points:
      - evo  =  evo.main_evo:main
      - evo_ape  =  evo.entry_points:ape
      - evo_config  =  evo.main_config:main
      - evo_fig  =  evo.main_fig:main
      - evo_ipython  =  evo.main_ipython:main
      - evo_res  =  evo.entry_points:res
      - evo_rpe  =  evo.entry_points:rpe
      - evo_traj  =  evo.entry_points:traj

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - argcomplete
    - colorama
    - matplotlib-base
    - natsort
    - numexpr
    - numpy
    - pandas
    - pillow
    - pygments
    - pyyaml
    - rosbags >=0.9.20
    - scipy
    - seaborn
    - contextily

tests:
  - python:
      imports:
        - evo
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/MichaelGrupp/evo
  summary: Python package for the evaluation of odometry and SLAM
  license: GPL-3.0-or-later
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
